#ifndef __ESP_CONFIG_OVERWRITE_H

#ifdef __cplusplus
extern "C" {
#endif

// Task configurations
#define LED_UPDATER_TASK_STACK_DEPTH        2048

#define CAPACITIVE_SENSOR_TASK_STACK_DEPTH  2048

#define BUTTON_TASK_STACK_DEPTH             2048

#define CAPACITIVE_SENSOR_LED_UPDATE_DELAY  500

// Task notifications
#ifndef configTASK_NOTIFICATION_ARRAY_ENTRIES
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#else
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#endif

#define CAPACITIVE_SENSOR_LED_NOTIFICATION_WAIT_VALUE (0x01)
#define CAPACITIVE_SENSOR_LED_NOTIFICATION_VALUE (0UL)

#define NETWORK_LED_NOTIFICATION_WAIT_VALUE (0x02)
#define NETWORK_LED_NOTIFICATION_VALUE (1UL)

#define BUTTON_PRESSED_EVENT_NOTIFICATION_WAIT_VALUE (0x01)
#define BUTTON_PRESSED_EVENT_NOTIFICATION_VALUE (0UL)

#ifdef __cplusplus
}
#endif

#define __ESP_CONFIG_OVERWRITE_H
#endif // __ESP_CONFIG_OVERWRITE_H
