#ifndef __ESP_CONFIG_OVERWRITE_H

#ifdef __cplusplus
extern "C" {
#endif

// From sdkconfig.h
#ifndef CONFIG_FREERTOS_HZ
#define CONFIG_FREERTOS_HZ 100
#endif

// Task configurations
#define LED_UPDATER_TASK_STACK_DEPTH        2048

#define CAPACITIVE_SENSOR_TASK_STACK_DEPTH  2048

#define BUTTON_TASK_STACK_DEPTH             2048

#define CAPACITIVE_SENSOR_LED_UPDATE_DELAY  500

#define NETWORK_TASK_STACK_DEPTH            4098

// Task notifications
#ifndef configTASK_NOTIFICATION_ARRAY_ENTRIES
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#else
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#endif

#define CAPACITIVE_SENSOR_LED_NOTIFICATION_WAIT_VALUE (0x01)
#define CAPACITIVE_SENSOR_LED_NOTIFICATION_VALUE (0UL)

#define LED_ANIMATION_START_NOTIFICATION_WAIT_VALUE (0x02)
#define LED_ANIMATION_START_NOTIFICATION_VALUE (1UL)

#define BUTTON_INTR_EVENT_WAIT_VALUE (0x01)
#define BUTTON_INTR_EVENT_VALUE (0UL)

#define NETWORK_AP_START_WAIT_VALUE (0x01)
#define NETWORK_AP_START_VALUE (0UL)

#ifdef __cplusplus
}
#endif

#define __ESP_CONFIG_OVERWRITE_H
#endif // __ESP_CONFIG_OVERWRITE_H
